version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mongodb://mongo:27017/porto_alegre_alema?replicaSet=rs0
      NODE_ENV: production
      PORT: 3001
    depends_on:
      mongo:
        condition: service_healthy  # Aguarda o MongoDB ficar saudável
    restart: on-failure

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: porto_alegre_alema
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: |
        mongosh --eval "
          try {
            rs.status().ok
          } catch(e) {
            rs.initiate({_id:'rs0', members:[{_id:0, host:'mongo:27017'}]});
            sleep(2000);
            rs.status().ok
          }
        "
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  mongo-seed:
    image: mongo:6
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./docker/mongo-init:/docker-mongo-init
    command: ["mongosh", "mongodb://mongo:27017/porto_alegre_alema?replicaSet=rs0", "/docker-mongo-init/seed.js"]
    restart: "no"

volumes:
  mongo_data:
